### ISSUE TITLE
Use of of older version of repr_offset

### ISSUE THREAD

**Issue by ahmed-masud** [rodrimati1992/abi_stable_crates#102]
https://github.com/rodrimati1992/abi_stable_crates/blob/c52b07897ca27007213154fdd3fbd1e65a714543/abi_stable/Cargo.toml#L54

Should be 0.2.2.

This causes problems because repr_offset 0.2.1 had the silly bug on line 131 of having a semi colon in the code.  Can you push a fix please :-)

**Comment by marioortizmanero** [comment]
Closed by #103
