### ISSUE TITLE
Mark ref_as_nonnull function as unsafe

### ISSUE THREAD

**Issue by kitcatier** [rodrimati1992/abi_stable_crates#104]
Hello, I found a soundness issue in this crate.
https://github.com/rodrimati1992/abi_stable_crates/blob/5661b01d8706dcdd7d8b83b94ac48e277d9ae286/abi_stable/src/utils.rs#L75-L77
[https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.new_unchecked](url)
The unsafe method called needs to ensure that the parameter must be non-null, and the developer who calls the ref_as_nonnull function may not notice this safety requirement.
Marking them unsafe also means that callers must make sure they know what they're doing.

**Comment by rodrimati1992** [comment]
The function takes a reference, and references can't be null.
