### ISSUE TITLE
Compilation Error for README Example in 3 Separate Crates

### ISSUE THREAD

**Issue by Neightro** [rodrimati1992/abi_stable_crates#105]
I'm a newcomer to this crate. I noticed that the documentation mentioned that the interface and implementation generally reside in separate crates, so I was trying to get the example working in that fashion. I commented out the single-crate version of `load_root_module_in_directory` and uncommented the 3-crate version. However, `cargo build -p implementation` then results in:

```
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
   --> implementation/src/lib.rs:112:1
    |
112 | impl<T> Appender for RVec<T> {
    | ^^^^^^^^^^^^^^^^^^^^^-------
    | |                    |
    | |                    `RVec` is not defined in the current crate
    | impl doesn't use only types from inside the current crate
    |
    = note: define and implement a trait or new type instead
```

What would be the recommended solution? I don't have enough knowledge of abi_stable to answer that myself.

My example repository, if helpful: <https://github.com/Neightro/abi_stable_readme_example>

**Comment by rodrimati1992** [comment]
Yes, the READNE example is wrong, apparently I edited it without trying it out in actually separate crates.

I'll fix the code in the README, and make it so that there are crates in the examples directory to run.

**Comment by Neightro** [comment]
Perfect! Thanks for the quick response.
