### ISSUE TITLE
`Object<.., RArc, ...>` doesn't implement `Clone`

### ISSUE THREAD

**Issue by RustyYato** [rodrimati1992/abi_stable_crates#107]
I tried using `RawMessageHook_TO<'static, abi_stable::std_types::RArc<()>>` where `RawMessageHook_TO` is a `sabi_trait`. But when I try to clone it, I can't! 

The reason appears to be because [`impl<T> GetPointerKind for RArc<T>`](https://docs.rs/abi_stable/latest/abi_stable/pointer_trait/trait.GetPointerKind.html#impl-GetPointerKind-for-RArc%3CT%3E) specifies it as [`PK_SmartPointer`](https://docs.rs/abi_stable/latest/abi_stable/pointer_trait/struct.PK_SmartPointer.html) which only implements clone if the value type implements clone, but that is counter-productive to `RArc`!

Is there some way I can access the `RArc` to clone it? (`unsafe` is fine)

**Comment by RustyYato** [comment]
Currently, I'm hacking around this with some ugly `transmute`s to a local type with the same representation as `RObject`, but I would like something more official than this hack.

**Comment by rodrimati1992** [comment]
Well, the smallest thing that could be done is to add special cased methods to `RObject` and `DynTrait` to `clone` them when they wrap an `RArc`. 
With that, you could do `RawMessageHook_TO::from_sabi(raw_message_hook.obj.cloned())` to clone the trait object.
(this uses the fact that `#[sabi_trait]` trait objects have a `pub obj: RObject/DynTrait` field)

**Comment by RustyYato** [comment]
That would work! I can put up a pr to do that
