### ISSUE TITLE
Inconsistency between documentation and code implementation

### ISSUE THREAD

**Issue by YichiZhang0613** [rodrimati1992/abi_stable_crates#113]
I noticed a possible panics due to inconsistency between documentation and code implementation in abi_stable/src/type_layout/tl_functions.rs. The details can be found in the following code. The code does not check whether nth is out of bounds before using [nth].
```rust
/// # Panics
///
/// This function panics if `nth` is out of bounds
/// (when `nth` is greater than or equal to `self.len()`)
pub fn index(&'static self, nth: usize, shared_vars: &'static SharedVars) -> TLFunction {
        self.functions()[nth].expand(shared_vars)
}
```

**Comment by rodrimati1992** [comment]
`.functions()` returns a `&'static [CompTLFunction]`. The returned slice that's indexed with `[nth]` does the bounds checking. The panic is documented in the code you posted above.
