### ISSUE TITLE
Expose RRawMutex & RRawRwLock

### ISSUE THREAD

**Issue by jean-airoldie** [rodrimati1992/abi_stable_crates#23]
I'm in the process of writing various async primitives with a stable ABI and I would need the equivalent of parking_lot::RawMutex & parking_lot::RawRwLock.

I see that what I would need would basically be those two internal types:

https://github.com/rodrimati1992/abi_stable_crates/blob/510725a81b735d0bfebd7edc4affb3d3d1e30847/abi_stable/src/external_types/parking_lot/mutex.rs#L30-L31

https://github.com/rodrimati1992/abi_stable_crates/blob/510725a81b735d0bfebd7edc4affb3d3d1e30847/abi_stable/src/external_types/parking_lot/rw_lock.rs#L31-L32

However there is no (easy) way for me to replicate these types since `UnsafeOveralignedField` is private.

Would you accept a PR if I turn these into fully fledged types with `repr(C)` and expose them publicly? It would implement `lock_api::RawMutex`.

As a side question, why are these fields overaligned over usize? Is it because we don't know the real size of the type ahead of time, but since it is a mutex we know that its size will never exceed a atomic usize?

**Comment by rodrimati1992** [comment]
As I mentioned in [this comment on the pull request](https://github.com/rodrimati1992/abi_stable_crates/pull/24#issuecomment-543440590),this doesn't work.
