### ISSUE TITLE
Stable ABI for std::task::Waker

### ISSUE THREAD

**Issue by jean-airoldie** [rodrimati1992/abi_stable_crates#25]
This would be really useful for implementing async primitives since they often hold [wakers](https://doc.rust-lang.org/std/task/struct.Waker.html). Unsure if its actually possible though.

**Comment by rodrimati1992** [comment]
Hmm,well I think you should also ask someone who knows how futures work in detail about whether using futures across `cdylib`s can work.

Going from the public API alone:

[RawWaker's vtable](https://doc.rust-lang.org/std/task/struct.RawWakerVTable.html) has regular Rust function pointers in it,which aren't ffi-safe,That basically requires wrapping the Waker on one side and rewrapping it on the other,which can happen an unbounded amount of times.

I am not going to work on this,but if you want to work on it feel free to do it,and ask questions on the gitter(now that I discovered that I blocked the gitter script I will see your messages).

**Comment by jean-airoldie** [comment]
Cool thx.

**Comment by jean-airoldie** [comment]
I'm closing this since as far as I know its not really usable.

**Comment by marioortizmanero** [comment]
For anyone who comes across this issue, this *is* possible and it's implemented by the https://crates.io/crates/async_ffi crate.
