### ISSUE TITLE
How to design a plugin that may requires one trait from interface crate, and provides another in interface crate?

### ISSUE THREAD

**Issue by luojia65** [rodrimati1992/abi_stable_crates#31]
Recently I am developing for a massive embedded chip debugger software. I uses `abi_stable` to design its plugin system, because this software may allow users to install plugins for backends, interface adapters and chip targets. I could design one interface crate, but here are still two (or maybe three) types of plugin crates that I need to implement: 

1. Service provider plugins. They should rely on no interfaces (actually backed with operating systems or other native code), and provides services (maybe `trait`s) in interface crate;
2. Adapter plugins. They may rely on one or more interfaces, providing one or more interfaces at the same time. That could represent a protocol adapter, a hub or a switch as hardware;
3. Consumer plugins. They could rely on interfaces, but provides nothing. That could be a debug logger or devices for measuring. 

To make things clear I have an example. Users may plug a JTAG dongle onto USB slot, then connect target MCU board with this dongle.  So here I need three plugins. First one wraps WinUSB or other operating system specific functions to provide universal USB structures in interface crate. Second one wraps dongle protocol support that requires USB traits and provides JTAG traits. Third one requires JTAG and provides a universal chip target flash trait. Finally the application may enumerate all flash traits using all three plugins and pick one flash trait to perform the flash write command. 

Here I need to implement all three plugins. The first could be easy as it could be implemented as a trait object that could provide to interface crate, as examples in `abi_stable` project have done. But the second and third ones are somehow tricky (I haven't find a way) to write, because they not only provides interfaces like usual plugins, but also _requires_ one interface from the crate thus _somehow performs just like an application_. 

Is there existing solutions to my problem? Or how should I design a system that allows plugin to provide interface implementations as well as requires some interfaces? Please provide with useful suggestions or example code, thanks!  

--- 
This is a help-wanted issue. I don't know if it's proper to post it here; if not, please let me know. Thanks!

**Comment by rodrimati1992** [comment]
I haven't thought about how to design a plugin system beyond the basic "plugins are dynamic libraries that implement a fixed trait" style of plugin.
My problem is that I don't even know how this would look in a regular Rust library that doesn't use dynamic linking,and it's harder when you add abi_stable.

**Comment by luojia65** [comment]
@rodrimati1992 Yes this is considered as a dynamic library manager. That's usually somehow the same structure if we use any ABI standard.

**Comment by luojia65** [comment]
Many years ago when I was developing distributed system at Synapse I thought this system was useless and unnecessary, I didn't solve this problem at that time. After first release, users are not able to make plugins thus have to compile with their own code attached, resulting in many many branches and finally I was scolded badly by users for years only because I was their project developer. So after that I think it's necessary to write a plugin system like this to finish my project now.
