### ISSUE TITLE
RBox::into_box should require T: Unpin

### ISSUE THREAD

**Issue by afranchuk** [rodrimati1992/abi_stable_crates#40]
Since this method may move the inner value, it must be Unpin.

**Comment by rodrimati1992** [comment]
Why though? The equivalent code with `Box` doesn't impose an `Unpin` requirement
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=24b4e95c5a6bd91b4f234907eb8a9897
```rust
use std::marker::PhantomPinned;

struct Foo(PhantomPinned);

fn into_inner<T>(boxed: Box<T>) -> T {
    *boxed
}

fn main(){
    into_inner(Box::new(Foo(PhantomPinned)));
}
```

**Comment by afranchuk** [comment]
You're right, sorry for the spam. I just had a bug related to this and that jumped into my head. Carry on :)

**Comment by afranchuk** [comment]
Somewhat related, should `RBox` implement `Unpin` in the same way that `Box` does?

**Comment by rodrimati1992** [comment]
Don't think there's a reason to *not* do it, so I'm adding those impls to the [0.9 branch](https://github.com/rodrimati1992/abi_stable_crates/tree/0.9), which I hope to release within 48 hours.

**Comment by afranchuk** [comment]
Thanks! In the meantime I made a new type wrapper for it, as I should have been Pinning the value all along (it is an abi stable binary search tree map/set so it has parent node pointers).

You might want to add an equivalent `RBox::pin` method too. Not sure of other Pin-related things.
