### ISSUE TITLE
Is it possible for RBox<T> to allow T: ?Sized ?

### ISSUE THREAD

**Issue by afranchuk** [rodrimati1992/abi_stable_crates#41]
Wasn't sure if there was a specific reason why `RBox<T>` doesn't loosen the `Sized` constraint on `T`. If there is a reason I'd be interested to understand it, and I think it'd be good to include it in the documentation.

**Comment by rodrimati1992** [comment]
For any given `T: !Sized` type(like `str` or `[T]`), `*const T` doesn't have layout stable across compiler versions.

This may not be true for the specific case of pointers to [extern types](https://github.com/rust-lang/rfcs/blob/master/text/1861-extern-types.md) when those are stabilized.

Also,if they add some way to have custom `?Sized` types, `RBox` can't support those.

**Comment by afranchuk** [comment]
Oh yeah, good point. Sorry for pestering again :) In my specific case I wanted an `RBox<[T]>` so I'll just special case on that and use `RBox<RSlice<T>>` for it. Thanks for the extern types link though.
