### ISSUE TITLE
Update unsound DrainFilter and RString::retain

### ISSUE THREAD

**Issue by Qwaz** [rodrimati1992/abi_stable_crates#44]
Hello, we (Rust group @sslab-gatech) found a memory-safety/soundness issue in this crate while scanning Rust code on crates.io for potential vulnerabilities.

https://github.com/rodrimati1992/abi_stable_crates/blob/2bff3b3aaf6b35aa0b36a81d7d91bff786958aee/abi_stable/src/std_types/vec/iters.rs#L292-L320

https://github.com/rodrimati1992/abi_stable_crates/blob/2bff3b3aaf6b35aa0b36a81d7d91bff786958aee/abi_stable/src/std_types/string.rs#L636-L670

These two implementations are copy-pasted from Rust's standard library, and unfortunately it turns out that std implementations were containing soundness bugs (rust-lang/rust#60977 and rust-lang/rust#78498, respectively). Could you check them and update the respective part of this crate?

**Comment by rodrimati1992** [comment]
That you for reporting this, I'll be making the 0.9.1 patch in the [0_9_patch](https://github.com/rodrimati1992/abi_stable_crates/tree/0_9_patch) branch. I'll wait at least 18 hours before releasing the patch.

**Comment by Qwaz** [comment]
Thank you for the quick fix!

**Comment by rodrimati1992** [comment]
I've released the patch for this, so I'm closing this now.
https://github.com/rodrimati1992/abi_stable_crates/releases/tag/0.9.1
https://crates.io/crates/abi_stable/0.9.1
