### ISSUE TITLE
Stable ABI for floating point numbers

### ISSUE THREAD

**Issue by marioortizmanero** [rodrimati1992/abi_stable_crates#60]
I've noticed that there's an implementation of `StableAbi` for most basic types, such as `i32`, `u64`, etc with the `impl_for_primitive_ints` macro. However, `f64` isn't in that list, and neither is `f32`. In fact, `f64` isn't mentioned once in the whole repository.

If it helps, their size is always known as per the reference: https://doc.rust-lang.org/stable/reference/type-layout.html#primitive-data-layout. But it's true that they don't have a known representation: https://doc.rust-lang.org/stable/reference/type-layout.html#primitive-representations.

I'm guessing I have to use `std::os::raw::c_double` and `std::os::raw::c_float` instead of `f64`, but is there any way to make this easier to use? It seems to just be an alias to Rust's type (https://doc.rust-lang.org/std/os/raw/type.c_float.html), but I'm not sure if there are any guarantees.

Thanks!

**Comment by rodrimati1992** [comment]
Added independent impls of `StableAbi` for `f32` and `f64` [in the 0.10.3 patch release](https://github.com/rodrimati1992/abi_stable_crates/releases/tag/v0.10.3)
