### ISSUE TITLE
Sharing thread-locals?

### ISSUE THREAD

**Issue by kdy1** [rodrimati1992/abi_stable_crates#64]
Is there a way to share thread-local variables?

### Context

I'm trying to build a plugin system for swc ( https://swc.rs ) using abi_stable.

I want to provide exactly same api for plugin as core transforms, but core transforms use thread locals.

There are two important thread locals and both of them lives in `swc_common`.

---

I searched for thread local but failed to find one and thanks for a great library!

**Comment by rodrimati1992** [comment]
I don't have any idea how thread locals work, or if they can be safely made to work across dynamic libraries.

**Comment by kdy1** [comment]
I think I can split `swc_common` into plugin runner mode / plugin mode.
In runner mode, it exposes additional methods. (`extern "C" fn`)
In plugin mode, it calls exposed functions.


But it would be better if there's automated way to do it.

**Comment by kdy1** [comment]
I made a question to rust user forum about the way to workaround this.

https://users.rust-lang.org/t/sharing-a-crate-with-crate-type-dylib/66768

It's about using dynamic libraries to completely share code. If I can't use `dylib` to do it, I will create a macro to make everything `extern "C`.

I'm lefting a comment because I found that it's conceptually similar to what does abi_stable does.

api crate => `libswc_common.dylib`
implmentation crate => core runtime
user crate => plugin.dylib


Are you interested in this macro?

**Comment by rodrimati1992** [comment]
I'm not clear on what the scope of the macro is, `abi_stable` already has [a proc-macro attribute for making individual functions `extern "C"`](https://docs.rs/abi_stable/*/abi_stable/attr.sabi_extern_fn.html)

**Comment by kdy1** [comment]
Oh, thank you! 

I'll see if it's enough.

**Comment by kdy1** [comment]
I found another solution.
Passing trait for thread-local operations will work.

I wrote it down at https://github.com/swc-project/swc/issues/2635

Thanks for your help and great library!

**Comment by afranchuk** [comment]
@kdy1 Sorry for the bump, but this caught my eye while looking for another issue. https://docs.rs/plugin_tls/0.3.0/plugin_tls/ allows you to share thread locals across binaries.
