### ISSUE TITLE
`StableAbi` for `Box<T>`

### ISSUE THREAD

**Issue by kdy1** [rodrimati1992/abi_stable_crates#65]
The documentation at https://doc.rust-lang.org/nightly/std/boxed/index.html#memory-layout says

> So long as T: Sized, a Box<T> is guaranteed to be represented as a single pointer and is also ABI-compatible with C pointers

So it can be implemented for some cases.

**Comment by rodrimati1992** [comment]
But it can't be dropped in Rust dynamic libraries where the global allocator is different.

**Comment by kdy1** [comment]
I see, thanks!
