### ISSUE TITLE
Build broken on <=1.45.0

### ISSUE THREAD

**Issue by h33p** [rodrimati1992/abi_stable_crates#66]
Hey there, it seems like `0.10` build is broken on older versions of Rust. The issue stems from several const fns in [nul_str.rs](https://github.com/rodrimati1992/abi_stable_crates/blob/master/abi_stable/src/sabi_types/nul_str.rs) that do branching. 0.9 works fine. Seems like travis-ci does not do any builds.

**Comment by rodrimati1992** [comment]
> Had to bump the MSRV from 1.41.0 to 1.46.0 because fixing Rust nightly compatibility caused Internal Compiler Errors in older Rust versions.

https://github.com/rodrimati1992/abi_stable_crates#minimum-rust-version

**Comment by h33p** [comment]
That's fair, I totally missed it!
