### ISSUE TITLE
`StableAbi` for `c_void`

### ISSUE THREAD

**Issue by h33p** [rodrimati1992/abi_stable_crates#67]
Hey there, I'm attempting to integrate your (awesome) layout checking with CGlue. It seems like `core::ffi::c_void` does not have `StableAbi` implemented, though, which causes some problems. I currently have it hackfixed by borrowing the `()` implementation, but it would be really cool to have it upstream. I can go ahead and submit a PR if you'd like, but am not exactly certain which fields need to be customized apart from name and module strings.

**Comment by eggyal** [comment]
Isn't the whole raison d'être of this crate to enable Rust-to-Rust FFI?  In which case, why would one want to handle `c_void`?
