### ISSUE TITLE
Possible collaboration with Pipeline IDE?

### ISSUE THREAD

**Issue by ctzurcanu** [rodrimati1992/abi_stable_crates#8]
We are planning an eventual implementation of the Pipeline IDE graph execution for Rust. (Now it is only for Solidity and JS.) Your work here could be helpful, but I do not know Rust enough to know clearly how to use abi_stable_crates and to interface it into our work.

I can envision this as the ability to weave new functions and dylibs by using funcs already deployed in dylibs. All without writing a line of code: just visually editing the graph. Interesting and doable?

https://www.youtube.com/watch?v=-LHvdZZUrss

https://github.com/pipeos-one/pipeline

Any guidance is appreciated.

**Comment by rodrimati1992** [comment]
> I can envision this as the ability to weave new functions and dylibs by using funcs already deployed in dylibs. All without writing a line of code: just visually editing the graph. Interesting and doable?

Well,this project is currently for Rust-to-Rust ffi with type checking when loading a Rust dynamic library from Rust code,so I don't know what would be necessary to make it compatible with your library.

I would first need to know your needs in more detail before I can say whether I could add features to support your library,or whether it would be incompatible with abi_stable_crates.

**Comment by ctzurcanu** [comment]
As soon as I find exactly how to use your project, I will think if we can extend Pipeline to Rust to use it. I sure hope so.
You should also know that I looked at many ffi examples for Rust and none treated the exact case that we needed: Rust to Rust dynamic libs. I would love to continue communicating with you on details. But probably github issues is not the place. https://gitter.im/pipeos-one/pipeline or even my email... if you may.

**Comment by rodrimati1992** [comment]
Ok,I just started reworking code generation to make iterating over modules and functions within those modules easier.

**Comment by rodrimati1992** [comment]
I decided that I am not going to add any major features for reflection.
I am fine with doing minor things to support reflection,but I am not going to either make a large addition to the library to support reflection.

**Comment by ctzurcanu** [comment]
Also, I am sorry I did not help with this. Considered that I'm too busy to learn Rust... If you will have at some point a collection of what is needed to access the functions and some hooks, let me know. Keep up your good work!
