### ISSUE TITLE
Making `abi_stable`'s types covariant

### ISSUE THREAD

**Issue by marioortizmanero** [rodrimati1992/abi_stable_crates#81]
See #75 for an explanation as to why this issue needs to be resolved.

Here's an exhaustive list of the variance in `std_types`:

## RCow

- [x] `BorrowOwned` should be removed (see #80)

## RVec

- [x] `buffer: *mut T` should be changed to `Unique<T>`
- [x] `vtable: VecVTable_Ref<T>` should be made opaque

## RHashMap

- [x] `map: RBox<ErasedMap<K, V, S>>` requires fixing `RBox<T>` first
- [x] `vtable: VTable_Ref<K, V, S>` should be made opaque

## RBox

- [x] `data: *mut T` should be changed to `Unique<T>`
- [x] `vtable: BoxVtable_Ref<T>` should be made opaque

## RArc

- [x] `vtable: ArcVtable_Ref<T>` should be made opaque

## The rest

- `RBoxError_`, `RIoError`, `RIoErrorKind`, `RString`, `UTypeId`, `RDuration`, `RCmpOrdering`,  `RSeekFrom`: no generic parameters
- `RSliceMut`: should be left as invariant
- `RStr`, `RSlice`, `Tuple{1..4}`, `ROption`, `RResult`: already covariant

## Thoughts

About `*mut T`:

* Most of the changes to `Unique<T>` can work fine with `NonNull<T>` as well. However, `NonNull<T>` has weaker semantics than `Unique<T>`, and we can actually guarantee that the pointer is owned by that struct.

About the vtables:

* We can use `mem::transmute` over the vtable itself, rather than over each individual function it has.
* We should use `ErasedType` instead of `*const ()` for the opaque types, right?
* Can we make this an easier & safer task? For example, having an option in the vtable proc macros. Definitely for the future, though.
* Is it possible to avoid the `transmute`?

Others:

* We should add a new test file to make sure everything's covariant. And also make sure the new `unsafe` is documented properly.

@rodrimati1992, we can split up the work however you like, and if you have any advice, please let me know. Specially regarding how to fix the vtables properly, which I'm not quite sure how to do best.

**Comment by rodrimati1992** [comment]
All the checklisted items I've fixed in the [0_11 branch](https://github.com/rodrimati1992/abi_stable_crates/tree/0_11), except that they use `NonNull` instead of `Unique` because [there's no such `pub` type in `std`](https://doc.rust-lang.org/std/?search=Unique).

**Comment by marioortizmanero** [comment]
That is brilliant, @rodrimati1992. I've been using that branch for a bit; it works perfectly and exactly how I would expect it to. You're right that there's no `Unique` type in `std`, got confused there. Thanks a bunch for the help!

**Comment by darach** [comment]
Tip of the hat 🎩 to you @rodrimati1992 - you just made @marioortizmanero very happy!
