### ISSUE TITLE
Examples don't compile, and I need some help

### ISSUE THREAD

**Issue by ShayBox** [rodrimati1992/abi_stable_crates#97]
I'm a bit new to rust, so maybe this isn't a great beginner project, but the examples don't compile, and they're a little complicated to understand, maybe some less-generic examples using "new" cargo workspaces would help.  

I'm following [working_with_abi_stable](https://nullderef.com/blog/plugin-abi-stable/#_working_with_abi_stable) [source](https://github.com/marioortizmanero/pdk-experiments/tree/master/abi-stable-simple) which seems to compile and I mostly understand it.  

I'm trying to expand my own [project](https://git.shaybox.com/spotify-vrc-osc) which interfaces with OSC to send and receive messages, and I want to send the received messages to all loaded plugins and allow plugins to send messages to the core application which will send them off via OSC.

This example tries to load `libmin.so` but each plugin would be under a different name such as `libspotify.so` or `liblogger.so` for example, how would I load multiple plugins that have the exact same interface? The example interface being `MinMod` and `MinMod_Ref`

**Comment by ShayBox** [comment]
Also `abi_stable` uses a very old `once_cell` version (>=1.0.0, <1.10.0) which conflicts with `clap` (^1.12.0), `abi_stable` will not compile with many other dependencies, please expand compatibility.

**Comment by ShayBox** [comment]
I figured out how to load multiple matching plugins via #92  
Now I'm trying to add a buffer parameter `buf: [u8; 0x600]` but I get  
`the associated item 'STABLE_ABI' exists for struct 'GetTypeLayoutCtor<[u8; 1536]>', but its trait bounds were not satisfied the following trait bounds were not satisfied: '[u8; 1536]: abi_stable::StableAbi'`  
![image](https://user-images.githubusercontent.com/9505196/200499243-be935a43-7ad5-450c-ae74-ea94ee24da05.png)

**Comment by rodrimati1992** [comment]
> Now I'm trying to add a buffer parameter `buf: [u8; 0x600]` but I get
> `the associated item 'STABLE_ABI' exists for struct 'GetTypeLayoutCtor<[u8; 1536]>', but its trait bounds were not satisfied the following trait bounds were not satisfied: '[u8; 1536]: abi_stable::StableAbi'`

That's simple, abi_stable 0.10 has a minimum required version of 1.46.0 and requires that you enable stuff that uses const generics with either of these crate features:
`"rust_1_51"` or `"rust_latest_stable"`

**Comment by ShayBox** [comment]
Ah thank you, that's what I needed 👍
